{"name": "test_post_message_without_body", "status": "broken", "statusDetails": {"message": "AttributeError: 'set' object has no attribute 'items'", "trace": "def test_post_message_without_body():\n        session_id = str(uuid.uuid4())\n        headers = {\n            f\"Cookie: session-id={session_id}\"\n        }\n    \n>       response = requests.post(BASE_URL, headers=headers)\n\ntests/backend/test_api.py:66: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/api.py:115: in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/api.py:59: in request\n    return session.request(method=method, url=url, **kwargs)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/sessions.py:575: in request\n    prep = self.prepare_request(req)\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/sessions.py:484: in prepare_request\n    p.prepare(\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py:368: in prepare\n    self.prepare_headers(headers)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <PreparedRequest [POST]>, headers = {'Cookie: session-id=ec8ff9b1-6c05-4f49-8c68-3fbf27144149'}\n\n    def prepare_headers(self, headers):\n        \"\"\"Prepares the given HTTP headers.\"\"\"\n    \n        self.headers = CaseInsensitiveDict()\n        if headers:\n>           for header in headers.items():\nE           AttributeError: 'set' object has no attribute 'items'\n\n/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/requests/models.py:488: AttributeError"}, "start": 1734533359142, "stop": 1734533359142, "uuid": "c92cb620-abaa-4ecb-91be-a0a1801f32f3", "historyId": "c8c8b8039f9322d75aebe79eedaae429", "testCaseId": "c8c8b8039f9322d75aebe79eedaae429", "fullName": "tests.backend.test_api#test_post_message_without_body", "labels": [{"name": "parentSuite", "value": "tests.backend"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "Mac"}, {"name": "thread", "value": "56128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.backend.test_api"}]}